[build]
  command = "npm run build"
  publish = "dist"
  # If you plan to use Netlify Functions for server-side logic, set the folder here
  # functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
